CREATE DATABASE keycloak;
CREATE DATABASE pedidosdb;

CREATE USER admin WITH PASSWORD 'Senh4Turm4#1';
GRANT ALL PRIVILEGES ON DATABASE keycloak TO admin;

\c keycloak;

GRANT USAGE ON SCHEMA public TO admin;
GRANT CREATE ON SCHEMA public TO admin;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO admin;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO admin;